# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-22.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-22.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest"}
          - {os: ubuntu-20.04, r: '3.6',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:	
      R_CHECK_FORCE_SUGGESTS: false
      R_CHECK_CRAN_INCOMING_REMOTE: false
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install system dependencies (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install cairo
          brew install --cask xquartz
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, markovchain=?ignore-before-r=4.0.0, Hmisc=?ignore-before-r=4.1.0, 
          needs: check

      - name: Install soilDB from r-universe (devel+3.6 only)
        if: matrix.config.r == '3.6' || matrix.config.r == 'devel'
        run: |
          install.packages("soilDB", repos = 'https://ncss-tech.r-universe.dev')
        shell: Rscript {0}
        
      - name: Install markovchain from MRAN (3.6 only)
        if: matrix.config.r == '3.6'
        run: |
          install.packages(c('matlab', 'expm', 'RcppParallel'))
          install.packages("https://cran.microsoft.com/snapshot/2020-04-23/src/contrib/markovchain_0.8.4.tar.gz", repos = NULL)
        shell: Rscript {0}
        
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
        
